### ISSUE TITLE
Add missing events to annotatedTRC2bids

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#10]
The following events are not yet parsed by the code:
- Slawtrans_on;/Slawtrans_off;
- Count_on;/Count_off; (with task annotation similar to #6)
- Sens_on;/Sens_off; (with task annotation similar to #6)
- Eyes_open;/Eyes_closed;

Possibly also language tasks need on/off tags (not yet specified in pipeline).

**Comment by dvanblooijs** [comment]
which ones have you used during annotation lately? I will only include the ones used ;).

**Comment by PauluzzS** [comment]
I have used slawtrans, eyes open for sure.
Sens only a few times. Count not.

**Comment by dvanblooijs** [comment]
At this moment, we use Eyes_open;/Eyes_close only during sleep when a patient is not really waking up, but opens his/her eyes. Therefore, Eyes_open is starting an epoch for eyes open, which is closed by Eyes_close. The period eyes closed is not further defined. 
This should be reconsidered when persons are annotating eyes closed periods during being awake.

**Comment by dvanblooijs** [comment]
I included sens_on and off as well as slawtrans. These should all appear in the events.tsv.
