### ISSUE TITLE
Match annotation to pipeline definition for some tags, or allow all variants

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#11]
There is a difference between:
- `Motor_on; `<->` Mt_on;`
- `ESM_on;` <-> `Stim_on;`
And corresponding `_off ` tags.

Perhaps multiple patterns can be defined to catch all variants, as `contains(STR,PATTERN)` accepts string arrays and cell array of character vectors.

**Comment by dvanblooijs** [comment]
I updated Mt_on and off with Motor_on and off, and Stim_on and off with ESM_on and off and SPES_on and off.
