### ISSUE TITLE
add Bad_HF annotation?

### ISSUE THREAD

**Issue by WillemiekZ** [dvanblooijs/ieeg_respect_bids#17]
I have added an annotation Bad_HF to mark channels in that are noisy in the high (FR) frequency ranges. Could you add it to the trc2bids script? As non-obligatory? I wouldn't add them to the channels that are bad in the conventional frequency ranges, but add an extra column to the table? 
I can also code it myself if you wish, let me know!

**Comment by dvanblooijs** [comment]
Bad_HF is added to scripts for converting to bids. In channels.tsv, it will now have bad_hf in status when Bad_HF  is described. Status description will be 'noisy in high frequency bands >120Hz&<500 Hz (visual assessment)'
