### ISSUE TITLE
extract_group_info throws matrix dimension error for 1 file

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#19]
Error in func:extract_group_info:
`Paul_annotation/Patients/PAT_2/EEG_138.TRC err:Matrix dimensions must agree. --func:extract_group_info`

**Comment by PauluzzS** [comment]
Seems to be caused by idx_grid = ~idx_depths & ~idx_strips & metadata.ch2use_included;
idx_depths and idx_strips are both only 68 long, where they should be as long as metadata.ch2use_included (i.e. 133). The length of 68 is derived from metadata.ch_label, which in turn is extracted by extract_metadata_from_annotations from ch, which corresponds to deblank({header.elec.Name}');
In read_micromed_trc, the 68 is derived from header.Num_Chan, which is read directly from the TRC header. In other files header.Num_Chan = 133; so it seems a problem with the file, not the code...

**Comment by PauluzzS** [comment]
Solved by annotating `Included` in problematic file.

**Comment by dvanblooijs** [comment]
it is now possible that an extra headbox is added in later ECoG-files without giving this error.
