### ISSUE TITLE
Traces without events or triggers throw an error

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#20]
`Undefined function or variable 'duration'. --func:write_annotations_tsv`
I suppose this only happens if there are no events in a trace.

**Comment by dvanblooijs** [comment]
how is that possible? No artefacts?

**Comment by dvanblooijs** [comment]
i fixed that events.tsv contains one line with n/a in all variables if no events occur in a trace
