### ISSUE TITLE
seizure on and offset in two different annotations, due to the high number of electrodes involved

### ISSUE THREAD

**Issue by dvanblooijs** [dvanblooijs/ieeg_respect_bids#23]

**Comment by dvanblooijs** [comment]
for example RESP0441

**Comment by WillemiekZ** [comment]
I also had a patient like this, and 'solved' it (will push code later). 
Still need to make it work for more than one Sz in one file with different numbers of Sz_on/off annotations.

**Comment by dvanblooijs** [comment]
I fixed it for multiple seizures in one file, will push the code within an hour.
