### ISSUE TITLE
extract_metadata_from_annotations throws error in absence of triggers

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#3]
"Index in position 1 exceeds array bounds." 
Probably because 
```
    trig_pos=trigger(1,:);
    trig_v=trigger(2,:);
```
on line 1109 doesn't work without triggers in the file. `trig_pos` and `trig_v` seem to be unused variables in the function. Issue related to #2.

> smb-share:server=10.121.48.169,share=willemiek/Paul_annotation/Patients/PAT_2/EEG_84.TRC err:sub-RESP0561 err:Index in position 1 exceeds array bounds. --func:extract_metadata_from_annotations Dot indexing is not supported for variables of this type. --func:annotatedTRC2bids

**Comment by PauluzzS** [comment]
Also line 1278:1279:
```
    metadata.trigger.pos  = trigger(1,:)  ;
    metadata.trigger.val  = trigger(end,:);
```
fails on empty trigger matrix.

Perhaps a quick fix / solution would be to set `trigger=[nan;nan]` if no triggers are found. This will result in some `nan` values in the final metadata, though...

**Comment by dvanblooijs** [comment]
I added 
(~isempty(trigger))
trig_pos=trigger(1,:);
    trig_v=trigger(2,:);
else
trig_pos=[];
    trig_v=[];
end
