### ISSUE TITLE
Channel specific artefacts with non-specific end annotation don't work

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#5]
If Art_on;C[14] is followed by Art_off;

> /home/paul/bulk/smb-share:server=10.121.48.169,share=willemiek/Paul_annotation/Patients/PAT_2/EEG_84.TRC err:sub-RESP0561 err:start and stop Art_on;C[14] does not match --func:look_for_annotation_start_stop sub-RESP0561 err:start and stop Art_on;C[14] does not match --func:look_for_annotation_start_stop --func:annotatedTRC2bids

See lines 1306:1324 in annotatedTRC2bids

annots:
> {[     51]}    {'Slawtrans_on;'   }
    {[    103]}    {'Run;day1'        }
    {[   1188]}    {'Task;sleep'      }
    {[   3428]}    {'Bad;C[25],CH[16]'}
    {[  12168]}    {'CLE_sz_trainset' }
    {[1750571]}    {'Art_on;'         }
    {[1761529]}    {'Art_off;'        }
    {[1933235]}    {'Slawtrans_off;'  }
    {[1933269]}    {'Sl_on;NREM;'     }
    {[4141325]}    {'Slawtrans_on;'   }
    {[4141360]}    {'Sl_off;'         }
    {[4679565]}    {'Art_on;C[14]'    }
    {[4731009]}    {'Art_off;'        }
    {[4785940]}    {'Art_on;C[14]'    }
    {[4911395]}    {'Art_off;'        }
    {[5699410]}    {'Art_on;C[14]'    }
    {[5771056]}    {'Art_off;'        }
    {[7588043]}    {'Art_on;'         }
    {[7592471]}    {'Art_off;'        }
    {[7663341]}    {'Art_on;'         }
    {[7666649]}    {'Art_off;'        }
    {[7868594]}    {'Slawtrans_off;'  }

**Comment by dvanblooijs** [comment]
this should not work, so that's correct. You should end an Art_on in a specific channel with an Art_off in a specific channel: for example: 'Art_on;C[14]' and 'Art_off;C[14]'. 'Art_off;' can only be used in combination with 'Art_on'.
