### ISSUE TITLE
Sleep annotation parse does not save (N)REM annotation

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#6]
sleep annotation is resolved using the `look_for_annotation_start_stop` function
As `look_for_annotation_start_stop` was written for artifacts, it looks for channels in the annotation instead of sleep stage (if specified).
This part of the function:
```
ch_art_idx=parse_annotation(annots{start_art(i),2},ch);

art.ch_names={ch{logical(ch_art_idx)}};
```
can be replaced in a new analogous function, with a line to extract whatever is after the `;` and check whether it is either REM or NREM, saving it to e.g. `art.sl_stage`

**Comment by dvanblooijs** [comment]
sleep, but also motor task will now allow a subtype (like REM/NREM)
