### ISSUE TITLE
Seizure annotation might have different ending channels

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#7]
Related to #5 , as seizure start and end tags are often different

Seizure parsing requires a separate read of channels in the end tag. The used function `look_for_annotation_start_stop`, only does a parsing of the start tag channels:
```
ch_art_idx=parse_annotation(annots{start_art(i),2},ch);    
art.ch_names={ch{logical(ch_art_idx)}};
```
should be repeated for `end_art` and saved to e.g. `art.end_ch_names`

**Comment by dvanblooijs** [comment]
this is solved for seizure annotations. For example: 'Sz_on;C[14]', 'Sz_off;C[6]' leads to a notation with ch_names_on = C14 and ch_names_off = C6.
