### ISSUE TITLE
'Format' annotation should not be mandatory

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#8]
Similarly to #4, line 1255:1258 look for format and throw an error if no format is annotated. 'Format' is considered compulsory, but isn't specified as such.

> '/home/paul/bulk/smb-share:server=10.121.48.169,share=willemiek/Paul_annotation/Patients/PAT_2/EEG_84.TRC err:sub-RESP0561 err:Missing Format annotation (example "Format;Gr[5x4];") --func:extract_metadata_from_annotations sub-RESP0561 err:Missing Format annotation (example "Format;Gr[5x4];") --func:extract_metadata_from_annotations --func:annotatedTRC2bids'

**Comment by PauluzzS** [comment]
if format is not annotated `metadata.format_info=[annots_format{:}];` also won't work. Maybe preallocate `annots_format` or not require it if no format annotation was found.

**Comment by dvanblooijs** [comment]
at least 1 ECoG file should contain Format. Format will remain mandatory
