### ISSUE TITLE
error while creating json sidecar for ieeg file: missing task_desc

### ISSUE THREAD

**Issue by PauluzzS** [dvanblooijs/ieeg_respect_bids#9]
> '/home/paul/bulk/smb-share:server=10.121.48.169,share=willemiek/Paul_annotation/Patients/PAT_2/EEG_84.TRC err:Undefined function or variable 'task_desc'. --func:annotatedTRC2bids'

Line 176 defines `cfg.TaskDescription             = task_desc;`
However, on line 97, `task_desc` is only created for task label containing SPES
```
        task_label    = strcat('task-',replace(deblank(metadata.task_name),' ',''));
        if strfind(task_label,'SPES')~=0
            task_desc = 'No task, rest';
        end
```

**Comment by dvanblooijs** [comment]
I added task descriptions, when 'sleep', 'rest', 'slawtrans' (transition between sleep and awake), 'motor' or 'ESM' is written in task_label.
